import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from "@/Componentes/Header";
import { Toaster } from "react-hot-toast";
import { headers } from "next/headers";
import { UserProvider } from "./Context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentPath = (await headers()).get("next-url") || "/";
  return (
    <UserProvider>
      <html lang="en" className="no-scrollbar">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-fondo `}
        >
          {currentPath !== "/" && <Header />}
          {children}
          <Toaster />
        </body>
      </html>
    </UserProvider>
  );
}
